### ISSUE TITLE
background from 'background" type instead of "features"

### ISSUE THREAD

**Issue by laresgod** [HeroCreationLab/hero-creation-tool#104]
with the evolution of the dnd5e module on vtt, 
and the dndbeyond importer,
backgrounds can be imported but they use the "background" type.

I would be nice for the hero creation tool to be able to accept input from that new type.

**Comment by ccjmk** [comment]
I totally missed this new issue, but it's almost done already.. just behind the scenes! 👀 I need to finish some parts but it should be releasing soon

**Comment by Wraithlord2015** [comment]
Just wondering the status on this? I know that it's being worked on - but unfortunately it's holding things up with getting my server up and running (manually importing doesn't work for everything).

**Comment by ccjmk** [comment]
backgrounds seem to be already working most of the way, I'm being a little halted by the advancement API so that they are reversible (with the provided Acolyte background, when you drag it into a character sheet, it will add the feature, but also will remove the feature if you remove the Background; that part needs a little wiring that I haven't had time to work on yet)

Worst-case scenario, I aim to deliver something this weekend, even if it's sadly half-baked; which would mean that if you remove a background added through the Creation Tool, it will not remove the feature and/or probably throw an error on the console, but you should be able to then remove the backgrounf feature manually. Same thing with Class Features (they basically rely on the same mechanism that I haven't tackled yet)
