### ISSUE TITLE
No pack for name [null]!

### ISSUE THREAD

**Issue by Wakarusa67** [HeroCreationLab/hero-creation-tool#124]
It looks like the same issue as posted by another user. Not sure how they resolved it.

**Comment by Wakarusa67** [comment]
I will add that I got it to work when I turned the forge game manager off. Not sure why that happened.

**Comment by ccjmk** [comment]
hmm there might be some weird interaction going on there. Sorry, I don't use the Forge, is the game manager a module in-game too, or just the tool from the website?

**Comment by ccjmk** [comment]
@Wakarusa67 have you been able to work around this ? I saw the user from the other issue where you initially reported this mentioned it got fixed by updating the module. If you have the latest version of the module, there's also a console command you can use to restore compendiums to defaults, if somehow they end up in an inconsistent state:
```js
 game.modules.get('hero-creation-tool').api.resetSources();
```

**Comment by ccjmk** [comment]
@Wakarusa67 I sadly will need to close this without any further info. If you are still having this problem, feel free to leave a message here so I can reopen the ticket and we can maybe see this together on Discord!
