### ISSUE TITLE
Hero creation tool don't work with 10.290 foundry update

### ISSUE THREAD

**Issue by Mirahel87** [HeroCreationLab/hero-creation-tool#131]
hi, i have a problem with hero creation tool after updating foundry vtt to version 10.290.
the module loads quietly but it can't read the various compendiums I have it handle.
it is as if it cannot access the various compendiums.
it is practically unusable as of today.
i hope you can update it with the new system because the module + very well done.

**Comment by ccjmk** [comment]
Sorry for the long reply, life had me otherwise occupied sadly, but I will try to start looking at these issues in between holidays! For reference, have you tried using the module without any other module loaded, as to discard any inter-module conflict?

**Comment by ccjmk** [comment]
Hi! I will need more information about this, I was finally able to get back my testing setup done, and a quick smoke test shows the module working as expected, at least with default compendia. I tried loading compendia imported from DDBImporter and it works, but the format of the files is a little odd, but definitely not the kind of error you are expecting.

My first suggestion is that something might have broken when changing versions, make sure you are on the latest stable version of foundry, and latest release of 5e (2.0.2), because my module is strictly dependent on some versions of the system. Not really much I can do about it, it's a module for 5e, sometimes they change something that break stuff for me, or add new stuff I need to use that is incompatible with older versions. That said, you can try to reset the default modules (that should solve a possible issue) by running this on the console:
```game.modules.get("hero-creation-tool").api.resetSources()``` (by default in Chrome you can open the console with F12, it should be easy to google if you use other browser).

If that works, try adding your compendia again, maybe just one category to try first , like.. just races, or just feats.

If you see any errors, please report back with any errors you see in the console. Hope this works!

**Comment by ottoh-commits** [comment]
Hi! 
Same problem here and here are more details.

I am using DDB Import and when I change the source folders to my DDB folders at settings, it gets error on opening the hero creation tool screen:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'level')
[Detected 1 package: hero-creation-tool]
    at spellsStep.ts:136:66
    at Array.filter (<anonymous>)
    at _Spells.setSourceData (spellsStep.ts:136:37)
    at async HeroCreationTool.setupData (heroCreationToolApp.ts:104:7)
    at async Object.fn (hero-creation-tool.ts:24:3)
```

It seems that something was missing when importing the spells, the item.system information has changed? I now so little about typescript and handful of javascript but hope this helps :) 

On a side note the command `game.modules.get("hero-creation-tool").api.resetSources()` helps but it of course only uses the 

My DnD5e version is 2.03 and Foundry VTT is version 10 build 287

**Comment by ccjmk** [comment]
Have you imported this in a previous version of foundry/5e ? Some recent changes in the structure of items made old items incompatible sadly :(

**Comment by ottoh-commits** [comment]
Yeah the problem was just that. This module works perfectly with the latest versions. 

DnD 5e 2.1.2
Foundry 10 build 291

Thanks!

**Comment by ccjmk** [comment]
@Mirahel87 I will need to close this given that I can't replicate the issue without further info. If you are still having issues, please leave a message and we can try to discuss it further on discord too.
