### ISSUE TITLE
Equipment missing

### ISSUE THREAD

**Issue by MythicalRollers** [HeroCreationLab/hero-creation-tool#142]
When adding equipment at the end of the builder, not everything in the compendium shows up.  Example, I just searched for "Leather" for armor and it did not show up in the search but is there in my compendium.
![image](https://user-images.githubusercontent.com/106455111/233233609-fefba4ef-1c3b-4a1d-bf58-fa2715c6e9e3.png)

**Comment by ccjmk** [comment]
Hmm I will need to investigate this; there's a filter that only Common items are shown, except for an explicit blacklist, here's the relevant code block:

```
this.items = filteredItems
      .filter((item) => item?.system?.rarity.toLowerCase() == 'common') // get only common items
      .filter((item) => !itemBlackList.includes(item.name)); // remove some punctual "common" but magical/special items
```
And the default blacklist is:
`'Potion of Climbing; Potion of Healing; Spell Scroll 1st Level; Spell Scroll Cantrip Level; Unarmed Strike'`

because these items are "common" but also magical of some sort (or.. well, Unarmed Strikes 🤷  hahahah)
so hopefully your Leather is just not `common`! if it's the case, then I'd need to investigate.

**Comment by MythicalRollers** [comment]
I see, my "Leather" had no flag.  Which is why it wasn't visible.  As soon as I put Common in the field it showed up.  Thank you for explaining the filter.  No need to investigate, ticket closed.  I wonder if there is a macro to update these things though. If blank update to Common lol.
