### ISSUE TITLE
Not all races show up in selection

### ISSUE THREAD

**Issue by mruks** [HeroCreationLab/hero-creation-tool#151]
Not all the races I have available, show up in the list. This happens both in the latest versions of v11 and v10.
See picture:
![image](https://github.com/HeroCreationLab/hero-creation-tool/assets/7190030/8418b22b-8486-4a8f-923d-2752ab62c2c0)

**Comment by mruks** [comment]
Hi, the video was helpful and when I remove the requirements, it indeed fixes it, but I did doublecheck the list and Air Genacy(Legacy) had just Genasi in there, which didn't work. To make it even weirder: if I add genasi to both, they just don't appear at all.
All the races I'm using are gotten through DDB importer, I have gone through a lot of the races and all of them have the requirement "racial feature" as feature type, which is something your video warns against doing.

**Comment by MythicalRollers** [comment]
In your images, you would need to have a race called "Genasi" for the Legacy to show up.  The reason the AG show up is because they do not have a required race.
I too imported races from DDB into my world.  There is a lot you have to fix if you want things to look clean.  DDBI will copy the same info as a core race, meaning if you have an Elf, and then have the High Elf look to Elf as a requirement, your High Elf in the builder will show the information from Elf, and for High Elf.  What I did with my races, was to keep the things that is shared between every subrace in the core "Elf", then I trimmed "High Elf" of any duplicate data like Keen Senses.  This way when I look at my High Elf, it does not show Keep Senses twice.  I also removed the feature.  There is a lot of work involved with what I did, but in the end, it looks cleaner in the builder.
