### ISSUE TITLE
Not able to select a Race

### ISSUE THREAD

**Issue by Dearion7** [HeroCreationLab/hero-creation-tool#161]
When I try to create a character with Hero Creation Tool I get the following issue: When I'm at the Race tab I can only choose None. He doesn't show the races I have.

In the Comendium Sources I have selected the following Race Compendia:
- DDB Races (Imported from the DDB Importer Module)
- Races (SRD)
- Races (Custom)

![image](https://github.com/HeroCreationLab/hero-creation-tool/assets/25343611/d3062b1c-ea81-449d-a3fe-c9eec883feea)

Please advise what I do wrong

**Comment by ccjmk** [comment]
Hi @Dearion7 ! If this is with the latest version of 5e that has integrated Race items, unfortunately I was not able to work on them yet. I am in need of some long holiday to get this back on track unfortunately. I will be posting an update as soon as I can.

**Comment by Dearion7** [comment]
No problem at all. Yes I run the latest version of 5e with integrated Race items. I just wanted to let you know. I will patiently wait for your update after your holiday.

**Comment by Gander7** [comment]
bumping since we are affected for when @Dearion7 gets a long holiday :)

**Comment by Dearion7** [comment]
> bumping since we are affected for when @Dearion7 gets a long holiday :)
> 
> EDIT: Let me know if there is anything I could work on to help with. I'm a full-stack developer but don't have experience with foundry modules.

Just a heads up. We are waiting on @ccjmk for when he get’s a long holiday to fix this. He is the developer for this module. 


I’m just a person using the module and found this issue.

**Comment by Gander7** [comment]
Yup, thanks for the correction, wasn't thinking when I tagged :)

**Comment by softwareplumber** [comment]
So... to summarize, the module is completely useless until someone has time to fix this? Sorry to sound excessively negative, I'm new to Foundry and I'm just trying to get everything working. Maybe there is some not-latest version of the 5e SRD races I can use?

**Comment by ccjmk** [comment]
Well I can spoil that I am actually working on this!  
![image](https://github.com/HeroCreationLab/hero-creation-tool/assets/4467128/3672f045-f8e5-434f-91ba-b5f085c8eb4e)

But it will still take some time for a new version to be available as it's a big change behind the curtains. I haven't tried what you suggest as workaround but I expect to find some errors anyway because of things that changed inside the system that this module was relying on. I will give this a try asap and let you know if it's a valid workaround.

**Comment by softwareplumber** [comment]
Well, sending telepathic espresso shots your way.  LMK if I can help, I'm a pretty Typescript developer.

**Comment by ccjmk** [comment]
Well I certainly appreciate the offer! :D right now the code is a "little" absolute mess that I'm trying to clean up but if I can get it to a state where I think it'd be easy and reasonable to parallelize some work I might reach you back!

**Comment by iLLHunter** [comment]
I am also affected by this

**Comment by tomsihap** [comment]
Hi @ccjmk , any updates on this? I guess we are many to be able to help, maybe you can provide a draft PR from where we can go on?

Regards

**Comment by vampiregoat699** [comment]
> When I try to create a character with Hero Creation Tool I get the following issue: When I'm at the Race tab I can only choose None. He doesn't show the races I have.
> 
> In the Comendium Sources I have selected the following Race Compendia:
> 
> * DDB Races (Imported from the DDB Importer Module)
> * Races (SRD)
> * Races (Custom)
> 
> ![image](https://private-user-images.githubusercontent.com/25343611/287460520-d3062b1c-ea81-449d-a3fe-c9eec883feea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NDQxNTAsIm5iZiI6MTcxOTQ0Mzg1MCwicGF0aCI6Ii8yNTM0MzYxMS8yODc0NjA1MjAtZDMwNjJiMWMtZWE4MS00NDlkLWEzZmUtYzllZWM4ODNmZWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDIzMTczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NTFjNTg4YTI0ZGNkOWZhZWFkYzZkZThlYTE3ZjlmZmU4MjUwOWVkYTg3MGViNTJjYzAwOTk1ZGE4NzYyZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HWfrYBGT3IYXtD5jzsN6sUl1fVHytHiEcDDLbjs7Ubo)
> 
> Please advise what I do wrong

I am also having an issue using this in Foundry v12 as no matter what I do no races appear for me to select.

**Comment by gregoryn22** [comment]
> Agreed with what @tomsihap said. I'm sure there are quite a few of us that could help. This is a blocker for me as well. Considering pulling the code and just fixing it myself since its been 5 months and no word from @ccjmk.

If I knew something besides python I'd tag in on this... I assume the race fix is abandoned

**Comment by ccjmk** [comment]
@gregoryn22 @tomsihap @vampiregoat699 @Brandin-Canterbury sorry for the long delay, somehow I got my email notifications turned off. 

This project has being discontinued, as you might have guessed, but part of why it was not updated is because someone else took over and redid most of the logic from scratch on a new project, [Actor Studio](https://github.com/geoidesic/foundryvtt-actor-studio), taking what was strictly necessary from here and having the benefit of a clean slate to handle things I was having trouble retrofitting into the existing module (mostly, Advancements)

I honestly forgot to post some update here pointing here towards that, but I will soon. Sorry again for the delay, and I hope you guys can use Actor Studio for your needs!
