### ISSUE TITLE
Unable to link Racial Features to Races

### ISSUE THREAD

**Issue by SecretSquirrel77** [HeroCreationLab/hero-creation-tool#20]

**Comment by ccjmk** [comment]
How exactly are you linking them ? I know that linking races/subraces/features is a little weird because you need to rely on the names, but there's sadly no alternative so far..
Here's an example with Drow Elves.

![image](https://user-images.githubusercontent.com/4467128/128309606-df44b512-dca8-40a9-9dc7-57a0dfd387c2.png)

Notice that the SUBrace has to contain the whole, exact name of the parent race both as part of the name and as Requirement.

So feature named Drow or Drow Elves would not work. And if it doesn't have exactly 'Elf' as requirement it won't work either.

then racial features need to have the exact race/subrace as requirement (and not having the race name as part of the feature name, else they would qualify as subraces).

If you are somehow still having problems, please feel free to reach back, I can always try to improve the documentation for these cases.

**Comment by ccjmk** [comment]
![image](https://user-images.githubusercontent.com/4467128/128310650-13768204-5a14-4246-9f82-65a157921b66.png)
Another example to make it clearer, just in case.

**Comment by SecretSquirrel77** [comment]
Got it now, thank you!
