### ISSUE TITLE
Window Resizer

### ISSUE THREAD

**Issue by SecretSquirrel77** [HeroCreationLab/hero-creation-tool#21]
Cannot resize window, even with popout resizer. Does not appear compatible with popout. The scrollbar in the app window will not allow you to see the entire description that is pulled up (Race, Class, etc.).

**Comment by ccjmk** [comment]
Hey SecretSquirrel, I am not absolutely sure if everything you mention here has to do with PopOut! module, but sadly the module is definitely not compatible with PopOut! - as they mention on their [Compatibility](https://github.com/League-of-Foundry-Developers/fvtt-module-popout#compatibility) section, modules accessing HTML elements will break, and we make extensive use of those :/

About resizing the main window within Foundry itself, I fixed it in size initially because it made styling easier, but I will look into polishing some of the CSS to allow resizing.

**Comment by SecretSquirrel77** [comment]
This module is amazing, by the way! Yes please consider CSS modification to allow players to see the entire description inside the feature they are browsing or adding.
