### ISSUE TITLE
Backgrounds with multiple features.

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [HeroCreationLab/hero-creation-tool#23]
**Feedback Type**: Bug
 
**Core:** 0.8.8
**System:** dnd5e v1.4.1
**Module Version:** hero-creation-tool v1.1.0
 
**Description**:
When there are multiple features for a background that particular background is listed multiple times under Background Name. When selecting the first listing the first feature is filled in. When selecting the second listing of the same background the feature is not working.<details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by ccjmk** [comment]
I am not sure what path to take to possibly fix this. In general, backgrounds give a single feature; so possible options I can see are:

a) Ignore any other backgrounds/features with the same background name.
b) List+add to character all the features for that background under a single name.
c) Alias each background so that if you have say, 'Feature A' and  Feature B'  for 'Soldier', they would show as two different backgrounds like 'Soldier(Feature A)' and 'Soldier(Feature B)'

Still, considering the ongoing work to incorporate background item types into the 5e system (https://gitlab.com/foundrynet/dnd5e/-/merge_requests/353) I think it would be best to wait and see how they implement it first. I understand it has a single feature ID field, so it would work closer to A or C, but if you think having multiple features under the same background is valuable, consider joining the conversation there and asking for an array of features instead of a single id.

**Comment by ccjmk** [comment]
This is now possible with the upcoming Advancements, as the `Item Grant` advancement allows OOTB for multiple features.

I will be making sure multiple features get parsed and added to the created actor.
