### ISSUE TITLE
Ignore choosable options (Invocations / Infusions / Metamagic / Others?)

### ISSUE THREAD

**Issue by ccjmk** [HeroCreationLab/hero-creation-tool#54]
These options that have a level requirement (like Warlock invocations) get pulled into the character if its created on a sufficiently high level.

**Comment by maxobremer** [comment]
hi, had a question regarding this-ish? So at the moment you are able to pick a fighting style within this tool. would it be possible to copy that and rename it meta magic, eldritch invocations and subclasses? would it be possible to make it so that it will consider it a option feature if its name contains :

So for example Metamagic: Careful Spell contains a : so would considered an option for the feature before the : aka Metamagic


Love you guys' work, keep it up 👍

**Comment by ccjmk** [comment]
I think I should be able to generalize it, yes. I will try to add this on the next big version, probably 1.6.0, if I can pull it off without mayor issues!

**Comment by maxobremer** [comment]
So if I may ask, is this still in the pipeline or is it something that's too difficult to add?

**Comment by ccjmk** [comment]
This is definitely still on the pipeline, but before deciding on an implementation I will wait for the [Advancements epic](https://gitlab.com/foundrynet/dnd5e/-/issues/1353) on the 5e system to be complete, as it might impact directly how to implement this.
