### ISSUE TITLE
Panel fails to open - Windows and Linux builds

### ISSUE THREAD

**Issue by Potjoe-97** [HeroCreationLab/hero-creation-tool#91]
Hi, 

I'm encountering an issue with the module, and I don't really know what steps to give in order to reproduce it. 
The panel won't open, whether it is configured as an independant menu, or in the "Create actor" section. I tried 1.7.0 and 1.6.3, both on my windows and linux builds. 

Here is what I caught in my web browser : 

![Capture d’écran 2022-02-12 194854](https://user-images.githubusercontent.com/42873357/153724217-55fd3677-7277-4117-a4b9-81b29073a8af.png)

Hope this is of some help!

**Comment by ccjmk** [comment]
Hi! Are you using the french translation by any chance? I noticed some issue with that, as the french translation is no up-to-date and I think causes this issue. But I should investigate so it doesn't crash.

**Comment by Potjoe-97** [comment]
Yes, indeed I am using the french translation! What seems odd to me is that I tried to disabled all modules (including the french translations) except this one, and I had the same issue.

**Comment by ccjmk** [comment]
@Potjoe-97 I identified the issue as some mismatch between keys, the key `HCT.Class.Submit` used to be a final key (it mapped to a translated text) but now its a parent key, with another level of keys under it, and that was not updated on the `fr.json`.

I corrected that so that the module should work now. I noticed some errors to pick up some input names and etc, but it doens't seem to hamper the usage: the hero seems to get created with everything it should have.

Please do notice that the FR localization is currently deprecated, as it was becoming hard to keep it updated, not been myself a native french speaker. The idea was to move it into an independent module someone else could manage, but that hasn't happened just yet, applications still open though! :P
