### ISSUE TITLE
Breaks when option routePrefix is enabled

### ISSUE THREAD

**Issue by aklys** [HeroCreationLab/hero-creation-tool#96]
When I apply a routePrefix (I currently have it configured because it's the only way I've figured out how to get the reverse proxy to work in the config I have) it seems to stop the add-on from loading. Remove the routePrefix and starts functioning again.

**Comment by ccjmk** [comment]
Hi! I think this might be related to: https://github.com/HeroCreationLab/hero-creation-tool/issues/93

Can you check if you get the same error ? It's the only weird thing I'm loading that might be getting a prefix issue as far as I can tell.  As mentioned on the issue I linked, it should be easily solvable once the new 5e version releases, but I think that release might be slightly delayed which in turn delays my update. Are you able to try to manually patch it?

**Comment by aklys** [comment]
Yeah I tried the removal of the .. references as per #93 the issue no longer exists. I personally don't need it fixed urgently as I have other methods but just thought it was worth mentioning. But those changes would seem to clean it up so that it functions with the routePrefix.

**Comment by ccjmk** [comment]
Super! I'm closing this issue to keep track of this on the other one then, as mentioned there this will be fixed with the next release that depends on 5e v1.6.0 where that application is exposed by the system and I don't need to fetch it.
(sorry for the long reply btw, I read your reply that it was all good and relaxed a little! heheh)
