### ISSUE TITLE
Tradution for pt-BR

### ISSUE THREAD

**Issue by RonaldoBrum** [HeroCreationLab/hero-creation-tool#99]
Hello I translated the tool to my language (pt-br), I will attach the lang file here
[pt-BR.zip](https://github.com/HeroCreationLab/hero-creation-tool/files/8732631/pt-BR.zip)

**Comment by ccjmk** [comment]
Hi Ronaldo! thanks a lot for the contribution! unfortunately for maintanibility reasons we are not embedding the translations on the module no more - it makes it easier for the translation maintainers to keep them up to date and for me to build updates without needing to pester people or waiting for 3rd parties.

What I can suggest is you make a little module that just translates this (or this module + others, like the Japanese community does with their "this module translates everything" approach) so that you have full ownership of it and can make adjustments and updates without needing to go through here!
